- name: Install firefox
  become: true
  pacman:
    name:
      - firefox
      - firefox-developer-edition

- name: Install chromnium
  kewlfft.aur.aur:
    use: yay
    name:
      - google-chrome
      - brave-bin

- name: Chromnium browser flags
  template:
    src: flags.conf
    dest: "~/.config/{{ item }}"
    mode: 0644
  loop:
    - chrome-flags.conf
    - brave-flags.conf
