- name: Install commonly used packages
  become: true
  pacman:
    name:
      - fwupd
      - zsh
      - neovim
      - vim
      - git
      - tmux
      - ripgrep
      - jq
      - alacritty
      - copyq
      - fd

      ## System
      # Files
      - thunar
      - tumbler
      - thunar-volman
      - thunar-archive-plugin
      - thunar-media-tags-plugin

      # Bluetooth
      - blueberry

      # Programming language setup
      #   Ruby, Python, Erlang
      - libffi
      - libyaml
      - openssl
      - zlib
      - xz
      # https://github.com/asdf-vm/asdf-erlang
      - ncurses
      - glu
      - mesa
      - libpng
      - libssh
      - unixodbc
      - libxslt
      - fop

      ## Social
      - discord

      ## Browser
      - firefox
      - firefox-developer-edition

      ## Language
      - fcitx5
      - fcitx5-mozc
      - fcitx5-rime
      - fcitx5-configtool
      - fcitx5-gtk
      - fcitx5-qt

      # Chinese
      - rime-pinyin-zhwiki
      - rime-luna-pinyin
      - rime-pinyin-simp

- name: Install commonly used packages - AUR
  kewlfft.aur.aur:
    use: yay
    name:
      ## Security
      - 1password
      - 1password-cli

      ## Editor
      - visual-studio-code-bin

      ## Browser
      - google-chrome
      - brave-bin

      ## Social
      - whatsapp-for-linux

- name: Clone Doom Emacs
  git:
    repo: https://github.com/doomemacs/doomemacs
    dest: ~/.emacs.d
    update: false

- name: Clone elixir-ls repo
  git:
    repo: git@github.com:elixir-lsp/elixir-ls.git
    dest: ~/workspace/elixir-ls
    update: false

# Security
- name: Set ssh config
  template:
    src: security/ssh-config
    dest: ~/.ssh/config
    mode: 0644

# Language
- name: Configure fcitx5
  template:
    src: "fcitx5/{{ item }}"
    dest: "~/.config/fcitx5/{{ item }}"
  loop:
    - config
    - profile

- name: Set environment variables for fcitx
  become: true
  template:
    src: fcitx5/environment
    dest: /etc/environment

# Browsers
- name: Chromnium browser flags
  template:
    src: browser/chromnium-flags.conf
    dest: "~/.config/{{ item }}"
    mode: 0644
  loop:
    - chrome-flags.conf
    - brave-flags.conf
