- name: Install Sway and related packages
  become: true
  pacman:
    name:
      - sway
      - swayimg
      - waybar
      - wofi
      - xorg-xwayland
      - xorg-xlsclients
      - qt5-wayland
      - glfw-wayland

      # clipboard
      - wl-clipboard
      - clipman

      # Screenshots
      - grim
      - slurp

      # Screen recorder
      - wf-recorder

      # Brightness control
      - brightnessctl

      # waybar
      - otf-font-awesome

- name: Install Sway addons
  kewlfft.aur.aur:
    use: yay
    name:
      - wl-clipboard-history-git
      - libappindicator-gtk3
      - greetd
      - greetd-gtkgreet

- name: Create local systemd directory
  file:
    path: ~/.config/systemd/user
    state: directory
    recurse: true

- name: Create systemd user conf
  become: true
  template:
    src: sway/50-systemd-user.conf
    dest: /etc/sway/config.d/50-systemd-user.conf

- name: Create sway-session.target
  template:
    src: sway/session.target
    dest: ~/.config/systemd/user/sway-session.target
    mode: 0644
  notify:
    - Reload user systemd

- name: Create startup script after login
  become: true
  template:
    src: sway/sway-run
    dest: /usr/local/bin/sway-run
    mode: 0755

- name: Symlink grimshot
  file:
    src: /usr/share/sway/scripts/grimshot
    dest: ~/bin/grimshot
    state: link

# Greetd settings
# https://wiki.archlinux.org/title/Greetd
- name: Setup greetd config
  become: true
  template:
    src: "greetd/{{ item }}"
    dest: "/etc/greetd/{{ item }}"
  loop:
    - config.toml
    - environment
    - sway-config
    - gtkgreet.css

- name: Enable greetd
  become: true
  systemd:
    name: greetd
    enabled: true
