- name: Install Sway and related packages
  become: true
  pacman:
    name:
      - sway

      # Screenshots
      - grim
      - slurp

- name: Install Sway addons
  kewlfft.aur.aur:
    use: yay
    name:
      - waybar

- name: Install app indicator
  kewlfft.aur.aur:
    use: yay
    name:
      - libappindicator-gtk3

- name: Create local systemd directory
  file:
    path: ~/.config/systemd/user
    state: directory
    recurse: true

- name: Create sway-session.target
  template:
    src: sway-session.target
    dest: ~/.config/systemd/user/sway-session.target
    mode: 0644
  notify:
    - Reload user systemd

- name: Symlink grimshot
  file:
    src: /usr/share/sway/scripts/grimshot
    dest: ~/bin/grimshot
    state: link
