- name: Install Sway and related packages
  become: true
  pacman:
    name:
      - sway

      # Screenshots
      - grim
      - slurp

- name: Install Sway addons
  kewlfft.aur.aur:
    use: yay
    name:
      - waybar

- name: Install app indicator
  kewlfft.aur.aur:
    use: yay
    name:
      - libappindicator-gtk3
