- name: Install Sway and related packages
  become: true
  pacman:
    name:
      - sway

      # Screenshots
      - grim
      - slurp

      # Brightness control
      - brightnessctl

- name: Install Sway addons
  kewlfft.aur.aur:
    use: yay
    name:
      - waybar
      - libappindicator-gtk3
      - greetd
      - greetd-gtkgreet

- name: Create local systemd directory
  file:
    path: ~/.config/systemd/user
    state: directory
    recurse: true

- name: Create sway-session.target
  template:
    src: sway-session.target
    dest: ~/.config/systemd/user/sway-session.target
    mode: 0644
  notify:
    - Reload user systemd

- name: Symlink grimshot
  file:
    src: /usr/share/sway/scripts/grimshot
    dest: ~/bin/grimshot
    state: link

# Greetd settings
# https://wiki.archlinux.org/title/Greetd
- name: Setup greetd config
  become: true
  template:
    src: "greetd/{{ item }}"
    dest: "/etc/greetd/{{ item }}"
  loop:
    - config.toml
    - environment
    - sway-config
